# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/MYASUS2/Documents/MesProgs/Bastfen/bastfen.ui'
#
# Created: Sat Jun 20 11:29:27 2015
#      by: PyQt5 UI code generator 5.3.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Bastfen(object):
    def setupUi(self, Bastfen):
        Bastfen.setObjectName("Bastfen")
        Bastfen.resize(581, 450)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Bastfen.sizePolicy().hasHeightForWidth())
        Bastfen.setSizePolicy(sizePolicy)
        self.centralWidget = QtWidgets.QWidget(Bastfen)
        self.centralWidget.setObjectName("centralWidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralWidget)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 10, 581, 391))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.groupBox = QtWidgets.QGroupBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget1 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget1.setGeometry(QtCore.QRect(20, 30, 261, 161))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.loic_life = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        self.loic_life.setFont(font)
        self.loic_life.setObjectName("loic_life")
        self.gridLayout.addWidget(self.loic_life, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.loic_potions = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        self.loic_potions.setFont(font)
        self.loic_potions.setObjectName("loic_potions")
        self.gridLayout.addWidget(self.loic_potions, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 0, 1, 1)
        self.loic_weapon_name = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        self.loic_weapon_name.setFont(font)
        self.loic_weapon_name.setObjectName("loic_weapon_name")
        self.gridLayout.addWidget(self.loic_weapon_name, 2, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.loic_dmg = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        self.loic_dmg.setFont(font)
        self.loic_dmg.setObjectName("loic_dmg")
        self.gridLayout.addWidget(self.loic_dmg, 3, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.loic_ammunitions = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        self.loic_ammunitions.setFont(font)
        self.loic_ammunitions.setObjectName("loic_ammunitions")
        self.gridLayout.addWidget(self.loic_ammunitions, 4, 1, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox, 0, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.layoutWidget2 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget2.setGeometry(QtCore.QRect(20, 30, 261, 161))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_11 = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 0, 0, 1, 1)
        self.hugo_life = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        self.hugo_life.setFont(font)
        self.hugo_life.setObjectName("hugo_life")
        self.gridLayout_2.addWidget(self.hugo_life, 0, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 1, 0, 1, 1)
        self.hugo_potions = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        self.hugo_potions.setFont(font)
        self.hugo_potions.setObjectName("hugo_potions")
        self.gridLayout_2.addWidget(self.hugo_potions, 1, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.gridLayout_2.addWidget(self.label_15, 2, 0, 1, 1)
        self.hugo_weapon_name = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        self.hugo_weapon_name.setFont(font)
        self.hugo_weapon_name.setObjectName("hugo_weapon_name")
        self.gridLayout_2.addWidget(self.hugo_weapon_name, 2, 1, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.gridLayout_2.addWidget(self.label_17, 3, 0, 1, 1)
        self.hugo_dmg = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        self.hugo_dmg.setFont(font)
        self.hugo_dmg.setObjectName("hugo_dmg")
        self.gridLayout_2.addWidget(self.hugo_dmg, 3, 1, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.gridLayout_2.addWidget(self.label_19, 4, 0, 1, 1)
        self.hugo_ammunitions = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        self.hugo_ammunitions.setFont(font)
        self.hugo_ammunitions.setObjectName("hugo_ammunitions")
        self.gridLayout_2.addWidget(self.hugo_ammunitions, 4, 1, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_2, 0, 1, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setContentsMargins(120, 60, 120, -1)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pb_beat = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        self.pb_beat.setFont(font)
        self.pb_beat.setObjectName("pb_beat")
        self.gridLayout_3.addWidget(self.pb_beat, 0, 0, 1, 1)
        self.pb_drink = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        self.pb_drink.setFont(font)
        self.pb_drink.setObjectName("pb_drink")
        self.gridLayout_3.addWidget(self.pb_drink, 1, 0, 1, 1)
        self.pb_change_weapon = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        self.pb_change_weapon.setFont(font)
        self.pb_change_weapon.setObjectName("pb_change_weapon")
        self.gridLayout_3.addWidget(self.pb_change_weapon, 2, 0, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 1, 0, 1, 2)
        Bastfen.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(Bastfen)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 581, 23))
        self.menuBar.setObjectName("menuBar")
        self.menuMenu = QtWidgets.QMenu(self.menuBar)
        self.menuMenu.setObjectName("menuMenu")
        Bastfen.setMenuBar(self.menuBar)
        self.action_leave = QtWidgets.QAction(Bastfen)
        self.action_leave.setObjectName("action_leave")
        self.menuMenu.addAction(self.action_leave)
        self.menuBar.addAction(self.menuMenu.menuAction())

        self.retranslateUi(Bastfen)
        QtCore.QMetaObject.connectSlotsByName(Bastfen)

    def retranslateUi(self, Bastfen):
        _translate = QtCore.QCoreApplication.translate
        Bastfen.setWindowTitle(_translate("Bastfen", "Bastfen"))
        self.groupBox.setTitle(_translate("Bastfen", "Loïc"))
        self.label_2.setText(_translate("Bastfen", "Vie :"))
        self.loic_life.setText(_translate("Bastfen", "EFFACEUR"))
        self.label_3.setText(_translate("Bastfen", "Potions :"))
        self.loic_potions.setText(_translate("Bastfen", "EFFACEUR"))
        self.label.setText(_translate("Bastfen", "Arme :"))
        self.loic_weapon_name.setText(_translate("Bastfen", "EFFACEUR"))
        self.label_4.setText(_translate("Bastfen", "Attaque :"))
        self.loic_dmg.setText(_translate("Bastfen", "EFFACEUR"))
        self.label_5.setText(_translate("Bastfen", "Munitions :"))
        self.loic_ammunitions.setText(_translate("Bastfen", "EFFACEUR"))
        self.groupBox_2.setTitle(_translate("Bastfen", "Hugo"))
        self.label_11.setText(_translate("Bastfen", "Vie :"))
        self.hugo_life.setText(_translate("Bastfen", "EFFACEUR"))
        self.label_13.setText(_translate("Bastfen", "Potions :"))
        self.hugo_potions.setText(_translate("Bastfen", "EFFACEUR"))
        self.label_15.setText(_translate("Bastfen", "Arme :"))
        self.hugo_weapon_name.setText(_translate("Bastfen", "EFFACEUR"))
        self.label_17.setText(_translate("Bastfen", "Attaque :"))
        self.hugo_dmg.setText(_translate("Bastfen", "EFFACEUR"))
        self.label_19.setText(_translate("Bastfen", "Munitions :"))
        self.hugo_ammunitions.setText(_translate("Bastfen", "EFFACEUR"))
        self.pb_beat.setText(_translate("Bastfen", "Loïc tape Hugo"))
        self.pb_drink.setText(_translate("Bastfen", "Loïc boit un coup"))
        self.pb_change_weapon.setText(_translate("Bastfen", "Loïc change d\'arme"))
        self.menuMenu.setTitle(_translate("Bastfen", "Menu"))
        self.action_leave.setText(_translate("Bastfen", "Quitter"))
        self.action_leave.setShortcut(_translate("Bastfen", "Ctrl+Q"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Bastfen = QtWidgets.QMainWindow()
    ui = Ui_Bastfen()
    ui.setupUi(Bastfen)
    Bastfen.show()
    sys.exit(app.exec_())

